config/routes.rb
Rails.application.routes.draw do
  get '/' => "home#top"
  get '/vata' => "home#vata"
  get 'login' => "user#login_form"
  post "login" => "user#login"
  get 'signup' => "user#signup"
  post 'signup' => "user#new"
  post "logout" => "user#logout"
  resources :words do
    collection do
      get :test
      get :learned_test
      get :favorite_test
      get :wrong_test
      get :result
      get :choice_test
      post :judge
      post :onfavorite
      post :unfavorite
      delete :destroy_all
      post :learned
      post :forgot
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def vata
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/top.html.erb
<% if @current_user %>
<% List.where(user_id: @current_user.id).destroy_all %>
<% Result.where(user_id: @current_user.id).destroy_all %>
<% Partofspeech.where(user_id: @current_user.id).destroy_all %>
<div class="menu">
  <div class="menu_box">
    <h1>Word Test</h1>
    <ul class="btn-field-1">
      <li><%= link_to 'Index', words_path, {class: "btn btn--orange btn--cubic btn--shadow index", onfocus: "this.blur();"} %></li>
    </ul>
    <ul class="btn-field-2">
      <li><%= link_to 'Create', new_word_path, {class: "btn btn--orange btn--cubic btn--shadow create", onfocus: "this.blur();"} %></li>
      <li><%= link_to 'Test', choice_test_words_path, {class: "btn btn--orange btn--cubic btn--shadow test", onfocus: "this.blur();"} %></li>
    </ul>
  </div>
</div>
<% else %>
<div class="menu">
  <div class="menu_box">
    <h1>Word Test</h1>
    <ul class="btn-field-2">
      <li><%= link_to 'Signup', "/signup", {class: "btn btn--orange btn--cubic btn--shadow index", onfocus: "this.blur();"} %></li>
      <li><%= link_to 'Login', "/login", {class: "btn btn--orange btn--cubic btn--shadow create", onfocus: "this.blur();"} %></li>
    </ul>
   </div>
</div>
<% end %>

app/views/home/vata.html.erb
<div class="centered">
  <div class="plus" id="plus">
    <div class="plus__line plus__line--v">
      <a href="#" class="plus__link ion-person"></a>
      <a href="#" class="plus__link ion-images"></a>
      <a href="#" class="plus__link ion-music-note"></a>
      <a href="#" class="plus__link ion-location"></a>
    </div>
    <div class="plus__line plus__line--h"></div>
  </div>
</div>