config/routes.rb
Rails.application.routes.draw do
  get '/' => "home#top"
  get '/vata' => "home#vata"
  get 'login' => "user#login_form"
  post "login" => "user#login"
  get 'signup' => "user#signup"
  post 'signup' => "user#new"
  post "logout" => "user#logout"
  resources :words do
    collection do
      get :test
      get :learned_test
      get :favorite_test
      get :wrong_test
      get :result
      get :choice_test
      post :judge
      post :onfavorite
      post :unfavorite
      delete :destroy_all
      post :learned
      post :forgot
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  validates:word, presence: true
  validates:meaning, presence: true
  validates:part_of_speech, presence: true
  validates_uniqueness_of :word, :scope => [:user_id, :part_of_speech],  conditions: -> { with_deleted }
  acts_as_paranoid

  def self.search(user,pos)
    where(user_id: user, part_of_speech: pos)
  end

  def self.nonsearch(user)
    where(user_id: user)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action:need_login

  
  def new 
    @word = Word.new
  end

  def create
    @word = Word.new(word_params)
    if @word.save 
      redirect_to new_word_path(part_of_speech: word_params[:part_of_speech])
    else
      render :action => "new"
    end
  end


  def index
    if params[:search].present?
    # 検索フォームからアクセスした時の処理
      search = Word.search(@current_user.id,params[:search])
      if params[:learned_and_forgot] 
        if (params[:favorited] && params[:learned]) || params[:favorited]
          @words = search.where(favorite: true).with_deleted.order(deleted_at: :desc)
        else
          @words = search.with_deleted.order(deleted_at: :desc)
        end
      elsif params[:learned] && params[:favorited]
        @words = search.where(favorite: true).only_deleted.order(deleted_at: :desc)
      elsif params[:learned]
        @words = search.only_deleted.order(deleted_at: :desc)
      elsif params[:favorited]
        @words = search.where(favorite: true)
      else
        @words = search.order(created_at: :desc)
      end
    else
    # 検索フォーム以外からアクセスした時の処理
      nonsearch = Word.nonsearch(@current_user.id)
      if params[:learned_and_forgot] 
        if (params[:favorited] && params[:learned]) || params[:favorited]
          @words = nonsearch.where(favorite: true).with_deleted.order(deleted_at: :desc)
        else
          @words = nonsearch.with_deleted.order(deleted_at: :desc)
        end
      elsif params[:learned] && params[:favorited]
        @words = nonsearch.where(favorite: true).only_deleted.order(deleted_at: :desc)
      elsif params[:learned]
        @words = nonsearch.only_deleted.order(deleted_at: :desc)
      elsif params[:favorited]
        @words = nonsearch.where(favorite: true)
      else
        @words = nonsearch.order(created_at: :desc)
      end
    end
  end

  def choice_test
    @part_of_speeches = ["動詞","名詞","形容詞","副詞","熟語"]
  end

  
  # 覚えたボタン
  def learned
    word = Word.find(params[:id])
    word.update(wrong_number: 0, count: 0)
    word.destroy #仮削除する
  end

  # 忘れたボタン
  def forgot
    word = Word.only_deleted.find(params[:id])
    word.restore #仮削除されたレコードを復元するメソッド
  end

  
#index画面でチェックボックスにチェックした単語を本当に削除するアクション
  def destroy_all
    if params[:deletes]
      params[:deletes].each do |data|
        Word.with_deleted.find(data).really_destroy! #.really_destroy! <- 本当に削除するメソッド
      end
      redirect_to request.referer
    else 
      redirect_to request.referer
    end
  end

#index画面で各リストの削除ボタンを押下したときに該当単語を本当に削除するアクション
  def destroy
    Word.with_deleted.find(params[:id]).really_destroy!
    redirect_to words_path
  end


  def update
    @word = Word.with_deleted.find(params[:id])
    @word.update(word_edit_params)
    respond_to do |format|
      format.html { redirect_to @word}
      format.json { render json: @word }
    end
  end

#テスト画面で示される選択肢を作成するアクション  
  def choices(name)
    #Wordテーブルからchoices2の返り値の品詞のデータを取ってきて、ランダムなデータを4つ取得する。そして取得したデータを単語の意味の配列にする
    @words_meaning = Word.with_deleted.where(user_id: @current_user.id, part_of_speech: name).order(Arel.sql("RANDOM()")).limit(4).map{|word| word.meaning}

    #@words_meaningリストに@random.meaningのデータが含まれていなかったら配列のランダムな位置の要素@random.meaningと入れ替える
    @words_meaning[rand(4)] = @random.meaning if @words_meaning.exclude?(@random.meaning)

    #上記のコードで取得したデータを元にListモデル（出題記録をつけるモデル）のインスタンスを作る
    List.create(word: @random.word, meaning: @words_meaning, user_id: @current_user.id)
    gon.number = @number = List.where(user_id: @current_user.id).count
  end

#テスト選択画面で選択した品詞を出力するアクション
  def choices2
    #テスト結果画面でもう一度ボタンを押されたときはテストに関係するモデルのレコードを削除する
    model_reset if params[:mark]
    #最初の問題のときのみPartofspeechモデル（ユーザーがテスト選択画面で選択した品詞、該当テストへのパスを保存するモデル）を作成
    Partofspeech.create(user_id: @current_user.id, name: params[:name], path: params[:path]) if List.where(user_id: @current_user.id).count == 0
    #品詞名を変数nameに代入
    name = Partofspeech.find_by(user_id: @current_user.id).name
    #出題された単語の配列であるlistword配列を作成する
    listword = List.where(user_id: @current_user.id).pluck(:word)
    return [name, listword]
  end 

#覚えていない単語のテスト画面のアクション
  def test
    #テスト画面のURLが直接入力されたらホーム画面に遷移する
    unless request.referer
      redirect_to "/"
    else
      #テスト画面で出題される単語を決定する。ユーザーがテスト選択画面で選択した品詞の単語であり、既に出題された単語でない単語である。さらに出題回数の少ない単語が選ばれる。
      @random = Word.search(@current_user.id,choices2[0]).where.not(word: choices2[1]).order(:count).first
      #該当の単語数が5つ未満の場合はテスト選択画面に戻る
      unless @random      
        redirect_to choice_test_words_path, flash: {error: "覚えたい単語(品詞：#{choices2[0]})の数が5つ未満になったためテストを中断しました" }
      else
        #出題回数を1増やす
        @random.update(count: @random.count + 1)
        #選択肢の単語の意味はchoices、choices2アクションで作成する
        choices(choices2[0])
      end
    end
  end

#覚えた単語のテスト画面のアクション
  def learned_test
    unless request.referer
      redirect_to "/"
    else
      @random = Word.only_deleted.where(user_id: @current_user.id, part_of_speech: choices2[0]).where.not(word: choices2[1]).order(:forgot_count).first
      unless @random      
        redirect_to choice_test_words_path, flash: {error: "覚えた単語(品詞：#{choices2[0]})の数が5つ未満になったためテストを中断しました" }
      else
        @random.update(forgot_count: @random.forgot_count + 1)
        choices(choices2[0])
        gon.learned = true
        render 'test'
      end
    end
  end

#お気に入り登録した単語のテスト画面のアクション
  def favorite_test
    unless request.referer
      redirect_to "/"
    else
      @random = Word.search(@current_user.id,choices2[0]).where(favorite: true).where.not(word: choices2[1]).order(:favorite_count).first
      unless @random      
        redirect_to choice_test_words_path, flash: {error: "お気に入りにした単語(品詞：#{choices2[0]})の数が5つ未満になったためテストを中断しました" }
      else
        @random.update(favorite_count: @random.favorite_count + 1)
        choices(choices2[0])
        gon.favorite = true
        render 'test'
      end
    end
  end

#間違えやすい単語のテスト画面のアクション
  def wrong_test
    unless request.referer
      redirect_to "/"
    else
      @random = Word.where(user_id: @current_user.id, part_of_speech: choices2[0], wrong_number: 2..Float::INFINITY).where.not(word: choices2[1]).order(wrong_number: "DESC").first
      unless @random      
        redirect_to choice_test_words_path, flash: {error: "間違えやすい単語(品詞：#{choices2[0]})の数が5つ未満になったためテストを中断しました" }
      else
        choices(choices2[0])
        gon.wrong = true
        render 'test'
      end
    end
  end

#テスト結果画面のアクション
  def result
    unless request.referer 
      redirect_to "/"
    else
      @results = Result.where(user_id: @current_user.id)
      @obj = Partofspeech.find_by(user_id: @current_user.id)
    end
  end

#テストの正誤を判定するアクション
  def judge
    #test.jsのajaxで送られたデータを使い問題の単語のレコードを検索
    question = Word.with_deleted.find(params[:question_id])
    q_meaning = question.meaning
    q_id = question.id
    #ユーザーが答えた解答が合っているか確認
    if q_meaning == params[:answer]
      test = {'test' => true}
      if Word.exists?(id: q_id)
        #合っていたら間違えた回数を1減らす
        question.update(wrong_number: question.wrong_number - 1)
      end
    else
      test = {'test' => false}
      if Word.exists?(id: q_id)
        #間違っていたら間違えた回数を1増やす
        question.update(wrong_number: question.wrong_number + 1)
      end
    end
    #結果画面で結果を出力するためのレコードを作成
    Result.create(answer: params[:answer], solution: q_meaning, user_id: @current_user.id, q_word: question.word, q_id: q_id)
    test['ans'] = q_meaning
    render :json => test
  end

  # お気に入り解除
  def unfavorite
    word = Word.with_deleted.find(params[:id])
    word.update(favorite: false, favorite_count: 0)
  end

  # お気に入り登録
  def onfavorite
    word = Word.with_deleted.find(params[:id])
    word.update(favorite: true)
  end



  private
  def word_params
    params.require(:word).permit(:word,:meaning,:user_id,:part_of_speech)
  end

  def word_edit_params
    params.require(:word).permit(:word,:meaning)
  end

end

app/helpers/word_helper.rb
module WordHelper
    def result_pop(maru)
        if maru == 5
            "excellent"
        elsif maru == 3 || maru == 4
            "good"
        else
            "bad"
        end
    end

    def result_number 
        maru_number = 0
        @results.each do |result|
            if result.answer == result.solution 
                maru_number += 1
            end
        end
        return maru_number
    end

    def model_reset
      List.where(user_id: @current_user.id).destroy_all 
      Result.where(user_id: @current_user.id).destroy_all 
      Partofspeech.where(user_id: @current_user.id).destroy_all 
    end
end

app/views/words/choice_test.html.erb
<% model_reset %>
<div class="choice_area">
  <% if flash[:error] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:error] %>
    <button type="button" class="close" data-dismiss="alert">&times;</button>
  </div>
  <% end %>
  <div class="select_box">
    <div id="select_area">
      <div class="choice_test_box">
      <div><a href="#" class="btn-animation-02"><span>覚えてない単語<span></a></div>
      <div class="hinsi-box">
      <% @part_of_speeches.each do |part| %>
        <%= link_to part, test_words_path(name: part, path: "test_words_path"), class: "test_btn #{part}-not-learned" %>
        <script>
          if (<%= Word.search(@current_user.id,part).count < 5 %>) { 
            $('.<%= part %>-not-learned').remove();
          }
        </script>
      <% end %>
      </div>
      </div>

      <div class="choice_test_box">
      <div><a href="#" class="btn-animation-02"><span>お気に入りにした単語<span></a></div>
      <div class="hinsi-box">
      <% @part_of_speeches.each do |part| %>
        <%= link_to part, favorite_test_words_path(name: part, path: "favorite_test_words_path"), class: "test_btn #{part}-favorite" %>
        <script>
          if (<%= Word.search(@current_user.id,part).where(favorite: true).count < 5 %>) { 
            $('.<%= part %>-favorite').remove();
          }
        </script>
      <% end %>
      </div>
      </div>

      <div class="choice_test_box">
      <div><a href="#" class="btn-animation-02"><span>覚えた単語<span></a></div>
      <div class="hinsi-box">
      <% @part_of_speeches.each do |part| %>
        <%= link_to part, learned_test_words_path(name: part, path: "learned_test_words_path"), class: "test_btn #{part}-learned" %>
        <script>
          if (<%= Word.search(@current_user.id,part).only_deleted.count < 5 %>) { 
            $('.<%= part %>-learned').remove();
          }
        </script>
      <% end %>
      </div>
      </div>

      <div class="choice_test_box">
      <div><a href="#" class="btn-animation-02"><span>間違えやすい単語<span></a></div>
      <div class="hinsi-box">
      <% @part_of_speeches.each do |part| %>
        <%= link_to part, wrong_test_words_path(name: part, path: "wrong_test_words_path"), class: "test_btn #{part}-wrong" %>
        <script>
          if (<%= Word.where(user_id: @current_user.id, part_of_speech: part, wrong_number: 2..Float::INFINITY).count < 5 %>) { 
            $('.<%= part %>-wrong').remove();
          }
        </script>
      <% end %>
      </div>
      </div>
    </div>
  </div>
</div>





app/views/words/index.html.erb
<% model_reset %>
<div class="index-area">
<div class="index-header">
<button type="button" class="filter-btn" onfocus="this.blur();" data-toggle="modal" data-target="#modal1">
<span class="fa-stack">
  <i class="far fa-square fa-stack-2x"></i>
  <i class="fas fa-filter fa-stack-1x"></i>
</span>
</button>
<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">条件検索</div>
            <div class="modal-body">
            <%= form_with url: words_path, method: :get, local: true do |f| %>
              <p><%= f.collection_select :search, Word.with_deleted.where(user_id: @current_user.id).select(:part_of_speech).distinct, :part_of_speech, :part_of_speech, {selected: params[:search], include_blank: '指定なし'} %></p>
              <p>
              <%= f.label :learned_and_forgot, "覚えた単語と覚えていない単語を表示" %>
              <%= f.check_box :learned_and_forgot, {}, true, nil %>
              </p>
              <p>
              <%= f.label :learned, "覚えた単語を表示" %>
              <%= f.check_box :learned, {}, true, nil %>
              </p>
              <p>
              <%= f.label :favorited, "お気に入り" %>
              <%= f.check_box :favorited, {}, true, nil %>
              </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <%= f.submit "絞り込み", class: "btn btn-primary" %>
            </div>
            <% end %>
        </div>
    </div>
</div>

<button type="button" class="filter-btn" onfocus="this.blur();" data-toggle="modal" data-target="#modal3">
<span class="fa-stack">
  <i class="far fa-square fa-stack-2x"></i>
  <i class="far fa-trash-alt fa-stack-1x"></i>
</span>
</button>

<button type="button" class="filter-btn" onfocus="this.blur();" data-toggle="modal" data-target="#modal4">
<span class="fa-stack">
  <i class="far fa-square fa-stack-2x"></i>
  <i class="fas fa-question"></i>
</span>
</button>

<div class="modal fade" id="modal4" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="m-header">Help</div>      
      <div class="m-body">
          <p>・<i class="fas fa-filter"></i>を押すと単語の条件検索ができます。<p>
          <p>・<i class="far fa-trash-alt"></i>を押すとチェックした単語の一括削除ができます。<p>
          <p>・単語一覧にある単語 or 単語の意味をクリックすると編集ができます。<p>
          <p>・右上にある検索バーに単語 or 単語の意味を入力すると該当する単語を検索することができます。<p>
          <p>・<i class="fas fa-search" style="color: black;"></i>をクリックすると選択した単語をgoogleで検索します。<p>
          <p>・<i class="fas fa-star" style="color: yellow;"></i>：お気に入り状態 , <i class="fas fa-star" style="color: #CCC;"></i>：お気に入り解除状態</p>
        </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="search-box">
  <input type="text" class="search-txt" placeholder="  search">
  <input type="button" value="&#xf002;" class="search-btn fas" >
</div>
</div>



<%= form_with url: destroy_all_words_path, method: :delete, local: true do |f| %>
<div class="table-area">
<table class="table index_table table-hover">
<thead>
  <tr>
    <th scope="col" class="align-middle" style="width: 5%; text-align: center"><input type="checkbox" name="allchecked" id="all" ></th>
    <th scope="col" class="align-middle"></th>
    <th scope="col" class="align-middle" style="width: 5%;"></th>
    <th scope="col" class="align-middle" style="width: 5%;"></th>
    <th scope="col" class="align-middle hide" style="width: 5%;"></th>
    <th scope="col" class="align-middle hide" style="width: 5%;"></th>
    <th scope="col" class="align-middle hide" style="width: 5%;"></th>
  </tr>
</thead>
  <tbody id="boxes">
    <% @words.each do |word| %>
    <tr style="height: 60px;">
      <td class="align-middle"><%= f.check_box :deletes, { multiple: true }, checked_value = word.id, unchecked_value = nil %></td>
      <td class="align-middle word">
        <p class='word_<%= word.id %>'><%= best_in_place word, :word, :as => :input, :html_attrs => { size: 5 } %></p>
        <p class="word-mean">(<%= word.part_of_speech.slice(0) %>) <span><%= best_in_place word, :meaning, :as => :input, :html_attrs => { size: 15 } %></span></p>
      </td>
      <td class="align-middle"><button  type="button" class="speakbtn_index" value=<%= word.id %> onfocus="this.blur();"><i class="fas fa-volume-up"></i></button></td>
      <% if word.favorite %>
        <td class="align-middle hide_btn"><div class=<%= word.id %>><i class="fas fa-star yellow"></i></div></td>
      <% else %>
        <td class="align-middle hide_btn"><div class=<%= word.id %>><i class="fas fa-star clear"></i></div></td>
      <% end %>

      <% if word.deleted_at == nil %>
        <td class="align-middle hide_btn">
          <div class=<%= word.id %>><i class="fas fa-check-circle fa-lg learned_btn" style="color: #C0C0C0"></i></div>
        </td>
      <% else %>
        <td class="align-middle hide_btn">
          <div class=<%= word.id %>><i class="fas fa-check-circle fa-lg forgot_btn" style="color: #8EB8FF"></i></div>
        </td>
      <% end %>

      <td class="align-middle hide_btn">
        <%= link_to word_path(id: word.id) , method: :delete, data: {confirm: "本当に削除しますか？"} do %>
          <i class="fas fa-trash-alt" style="color: black;"></i>
        <% end %>
      </td>
      <td class="align-middle hide_btn">
        <a href="https://www.google.com/search?q=<%= word.word %>" target="_blank" rel="noopener noreferrer"><i class="fas fa-search" style="color: black;"></i></a>
      </td>
      <td class="align-middle mix_btn">
        <div class="plus" id="plus">
          <div class="plus__line plus__line--v">
            <% if word.favorite %>
              <div class=<%= word.id %>><i class="fas fa-star yellow"></i></div>
            <% else %>
              <div class=<%= word.id %>><i class="fas fa-star clear"></i></div>
            <% end %>
            <% if word.deleted_at == nil %>
              <div class=<%= word.id %>><i class="fas fa-check-circle fa-lg learned_btn" style="color: #C0C0C0"></i></div>
            <% else %>
              <div class=<%= word.id %>><i class="fas fa-check-circle fa-lg forgot_btn" style="color: #8EB8FF"></i></div>
            <% end %>
            <div>
              <%= link_to word_path(id: word.id) , method: :delete, data: {confirm: "本当に削除しますか？"} do %>
                <i class="fas fa-trash-alt" style="color: black;"></i>
              <% end %>
            </div>
            <div><a href="https://www.google.com/search?q=<%= word.word %>" target="_blank" rel="noopener noreferrer"><i class="fas fa-search" style="color: black;"></i></a></div>
          </div>
          <div class="plus__line plus__line--h"></div>
        </div>
      </td>
      <div class="modal fade modal_delete_search" id="modal_delete_search_<%= word.id %>" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-body">
              <%= link_to word_path(id: word.id) , method: :delete, data: {confirm: "本当に削除しますか？"} do %>
                <i class="fas fa-trash-alt fa-2x" style="color: black;"></i>
              <% end %>
              <p>/</p>
              <a href="https://www.google.com/search?q=<%= word.word %>" target="_blank" rel="noopener noreferrer"><i class="fas fa-search fa-2x" style="color: black;"></i></a>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="modal fade" id="modal3" tabindex="-1" role="dialog" aria-labelledby="basicModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body">チェックしたデータを一括削除しますか？</div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <%= f.submit "OK", class: "btn btn-primary" %>
            </div>
        </div>
    </div>
</div>
<% end %>
</div>

app/views/words/new.html.erb
<% model_reset %>
<div class="create_box">
  <div class="word_create">
    <h1>Create Word</h1>
    <%= form_with model: @word, local: true do |f| %>
      <div class="create-form">
        <div class="create_field">
          <%= f.text_field :word, :placeholder => "word", :class => 'text_field', :value => @word.word %>
          <div class="error_box">
          <% if @word.errors.include?(:word) %>
          <p><%= @word.errors.full_messages_for(:word).first %></p>
          <% end %>
          </div>
        </div>

        <div class="create_field">
          <%= f.text_field :meaning, :placeholder => "meaning", :class => 'text_field', :value => @word.meaning %>
          <div class="error_box">
          <% if @word.errors.include?(:meaning) %>
          <p><%= @word.errors.full_messages_for(:meaning).first %></p>
          <% end %>
          </div>
        </div>
      </div>
      
      <div class="pull_down"><%= f.select :part_of_speech, options_for_select([["動詞", "動詞"],["名詞", "名詞"],["副詞", "副詞"],["形容詞", "形容詞"],["熟語", "熟語"]], params[:part_of_speech]) %></div>
      <%= f.hidden_field :user_id, :value => @current_user.id %>
      <div class="create_button"><%= f.submit 'CREATE', :class => 'btn btn--orange btn--cubic btn--shadow create', :onfocus => "this.blur();" %></div>
    <% end %>
  </div>
</div>

app/views/words/result.html.erb
<div class="result-area">
<div class="result_box">
  <p id="arch"><%= result_pop(result_number) %></p>
  <div id="result_circle"></div>
  <div class="again_box">
    <%= link_to  "NEXT", __send__(@obj.path, name: @obj.name, path: @obj.path, mark: "mark"), {class: "btn-square-slant"} %>
  </div>
</div>

<table class="table result-table">
  <tbody>
  <% @results.each_with_index do |result,index| %>
    <tr>
      <td scope="row" class="align-middle" style="width: 5%;"><%= index + 1 %></td>
      <% word = Word.with_deleted.find_by(id: result.q_id) %>
      <% if word.favorite %>
        <td class="align-middle" style="width: 5%;"><div class=<%= word.id %>><i class="fas fa-star yellow"></i></div></td>
      <% else %>
        <td class="align-middle" style="width: 5%;"><div class=<%= word.id %>><i class="fas fa-star clear"></i></div></td>
      <% end %>

      <% if Word.exists?(id: result.q_id) %>
        <td class="align-middle" style="width: 5%;">
          <div class=<%= result.q_id %>><i class="fas fa-check-circle fa-lg learned_btn_result" style="color: #C0C0C0"></i></div>
        </td>
      <% else %>
        <td class="align-middle" style="width: 5%;">
          <div class=<%= result.q_id %>><i class="fas fa-check-circle fa-lg forgot_btn_result" style="color: #8EB8FF"></i></div>
        </td> 
      <% end %>
      
      <td class="align-middle word" style="width: 70%;">
        <p class='q_word word_<%= result.id %>'><%= result.q_word %></p>
        <p class="word-mean"><%= result.solution %></p>
      </td>
      <td class="align-middle" style="width: 5%;"><button  type="button" class="speakbtn_index" value=<%= result.id %> onfocus="this.blur();"><i class="fas fa-volume-up"></i></button></td>

      <% if result.answer == result.solution %>
        <td class="align-middle" style="text-align: center; width: 5%;"><div class="maru">〇</div></td>
      <% else %>
        <td class="align-middle" style="text-align: center; width: 5%;"><div class="batu">✕</div></td>
      <% end %>

      <td class="align-middle" style="width: 5%;"><a href="https://www.google.com/search?q=<%= result.q_word %>" target="_blank" rel="noopener noreferrer"><i class="fas fa-search" style="color: black;"></i></a></td>
    </tr>
  <% end %>
  </tbody>
</table>
<div class="back_index"><%= link_to "テスト選択画面に戻る", choice_test_words_path, {class: "link_index"} %></div>
</div>

<script>
$(function() {
  var bar = new ProgressBar.SemiCircle("#result_circle", {
  strokeWidth: 6,
  color: '#FFEA82',
  trailColor: '#eee',
  trailWidth: 1,
  easing: 'easeInOut',
  duration: 1000,
  svgStyle: null,
  text: {
    value: '',
    alignToBottom: true
  },
  from: {color: '#FFEA82'},
  to: {color: '#ED6A5A'},
  // Set default step function for all animate calls
  step: (state, bar) => {
    bar.path.setAttribute('stroke', state.color);
    var value = Math.round(bar.value() * 100);
    if (value === 0) {
      bar.setText('');
    } else {
      bar.setText(value);
    }

    bar.text.style.color = state.color;
  }
});
bar.text.style.fontFamily = '"Raleway", Helvetica, sans-serif';
bar.text.style.fontSize = '2rem';

bar.animate(<%= result_number %>*0.2);  // Number from 0.0 to 1.0
$('#arch').arctext({radius: 400})
});

$(function () {
  if (<%= result_number %> == 5){
    document.querySelector("#excellent").play();
  }else if(<%= result_number %> == 3 || <%= result_number %> == 4 ) {
    document.querySelector("#good").play();
  }else{
    document.querySelector("#bad").play();
  }
});
</script>


app/views/words/test.html.erb
<div class="test-area1">
  <div id="container"></div>
  <div class="header-test">
    <p class="number"><%= @number %>/5</p>
    <div class="favorite-button">
    <% if @random.favorite %>
      <div class=<%= @random.id %>><i class="fas fa-star yellow"></i></div>
    <% else %>
      <div class=<%= @random.id %>><i class="fas fa-star clear"></i></div>
    <% end %>
    </div>
    <a href="https://www.google.com/search?q=<%= @random.word %>" class="search" target="_blank" rel="noopener noreferrer"><i class="fas fa-search" style="color: black"></i></a>
    <button id="speakbtn"><i class="fas fa-volume-up fa-lg"></i></button>
  </div>
</div>
  
<div class="test-area2">
  <div class="quiz_area">
      <div class="quiz_question">
        <div class="question">
          <p class="q_word"><%= @random.word %></p>
        </div>
      </div>
      <div class="next"></div>
      <div class="quiz_ans_area">
          <% @words_meaning.each do |meaning| %>
            <div class="choice_box"><a href="#!" class="word_mean"><%= meaning %></a></div>
          <% end %>
        <div class="quiz_area_bg"></div>
      </div>
      <div class="quiz_area_icon"></div><!-- 追加 マルバツを中央に表示させるエリア -->
  </div>
</div>

<script>
$(function() {
    var q_word = $('.q_word').text();
    const uttr = new SpeechSynthesisUtterance();
    uttr.text = q_word;
    uttr.lang = "en-US";
    speechSynthesis.speak(uttr);
});

$(function(){
  var bar = new ProgressBar.Line("#container", {
    strokeWidth: 0.7,
    easing: 'easeInOut',
    duration: 800,
    color: '#FFCC33',
    trailColor: '#eee',
    trailWidth: 0.7,
  });
  bar.set((<%= @number %>-1)*0.2);
  bar.animate(<%= @number %>*0.2); 
})


</script>