config/routes.rb
Rails.application.routes.draw do
  get '/' => "home#top"
  get '/vata' => "home#vata"
  get 'login' => "user#login_form"
  post "login" => "user#login"
  get 'signup' => "user#signup"
  post 'signup' => "user#new"
  post "logout" => "user#logout"
  resources :words do
    collection do
      get :test
      get :learned_test
      get :favorite_test
      get :wrong_test
      get :result
      get :choice_test
      post :judge
      post :onfavorite
      post :unfavorite
      delete :destroy_all
      post :learned
      post :forgot
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: { maximum: 13 }
  validates :password, presence: true, length: { minimum: 10 }
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def login_form
    @user = User.new
  end

  def login
    @user = User.find_by(name: user_login_params[:name])
    if @user && @user.authenticate(user_login_params[:password])
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render "user/login_form"
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to "/"
  end

  def signup
    @user = User.new
  end

  def new
    @user = User.new(user_signup_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render "user/signup"
    end
  end

  private
  def user_signup_params
    params.require(:user).permit(:name,:password,:password_confirmation)
  end
  def user_login_params
    params.require(:user).permit(:name,:password)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/login_form.html.erb
<div class="text-center">
  <main class="form-signin">
  <%= form_with model: @user, url: login_url, local: true do |f| %>
    <h1 class="h3 mb-3 fw-normal">login</h1>
    <%= f.label :name, "Username" %>
    <%= f.text_field :name, :class => 'form-control', :placeholder => "Username" %>
    <%= f.label :password, "Password", :class => 'visually-hidden' %>
    <%= f.password_field :password, :class => 'form-control', :placeholder => "Password" %>
    <%= f.submit 'login', :class => 'btn btn-lg btn-primary' %>
  <% end %>
  </main>
</div>



app/views/user/signup.html.erb
<div class="text-center">
<main class="form-signin">
<%= form_with model: @user, url: signup_url, local: true do |f| %>
  <h1 class="h3 mb-3 fw-normal">signup</h1>
  <%= f.label :name, "Username" %>
  <% if @user.errors.any? %>
    <p class="alert-message">※<%= @user.errors.full_messages_for(:name).first %></p>
  <% end %>
  <%= f.text_field :name, :class => 'form-control', :placeholder => "Username(13文字以内)", :value => @user.name %>
  <%= f.label :password, "Password", :class => 'visually-hidden' %>
  <% if @user.errors.any? %>
    <p class="alert-message">※<%= @user.errors.full_messages_for(:password).first %></p>
  <% end %>
  <%= f.password_field :password, :class => 'form-control', :placeholder => "Password(10文字以上)" %>
  <%= f.label :password_confirmation, "Password_Confirmation", :class => 'visually-hidden' %>
  <% if @user.errors.any? %>
    <p class="alert-message">※<%= @user.errors.full_messages_for(:password).first %></p>
  <% end %>
  <%= f.password_field :password_confirmation, :class => 'form-control', :placeholder => "Password(10文字以上)" %>
  <%= f.submit 'signup', :class => 'btn btn-lg btn-primary' %>
<% end %>
</main>
</div>
